apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-dep-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
       - image: {{ .Values.image.repository }}
         name: nginx
      imagePullSecrets:
        - name: regcred
